### ISSUE TITLE
feature request / extension

### ISSUE THREAD

**Issue by illucent** [bcmarinacci/powerline-shell#2]
Hi! 
```
# to indicate root account
if [[ $EUID == 0 ]] ; then
    readonly ra="$(tput setaf 255)$(tput setab 250)$EUID"
fi
```
and line 66 
`PS1+="${ra}${__ps_color_reset}${__ps_color_bg_base}${__ps_color_fg_base}  "`

**Comment by bcmarinacci** [comment]
Hey, mate, thanks for the suggestion! My goal is to keep this as minimalist and specific to my own use case for simplicity so I probably won't add any features that I don't use. Having said that, I appreciate the mention and you can definitely fork this repository and hack it to be whatever you want. 😊
